"""Global server installation: database, schema, owner admin."""

from __future__ import annotations

import asyncio
import os
import secrets
import subprocess
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Callable, Optional, Tuple

from .install_config import (
    apply_env_to_process,
    env_path,
    find_prisma_schema,
    get_app_dir,
    mark_setup_complete,
)

LogFn = Callable[[str], None]


@dataclass
class GlobalSetupConfig:
    organization_name: str
    db_host: str
    db_port: int
    db_user: str
    db_password: str
    db_name: str
    admin_username: str
    admin_password: str
    admin_email: str
    server_host: str = "0.0.0.0"
    server_port: int = 9000
    auto_start: bool = True
    open_browser: bool = True

    def database_url(self) -> str:
        from urllib.parse import quote_plus

        return (
            f"postgresql://{quote_plus(self.db_user)}:{quote_plus(self.db_password)}"
            f"@{self.db_host}:{self.db_port}/{self.db_name}"
        )

    def write_env_file(self) -> Path:
        secret = secrets.token_hex(32)
        api_origin = f"http://localhost:{self.server_port}"
        content = f"""# Generated by CyberCafe Global Server Setup
DATABASE_URL={self.database_url()}
SECRET_KEY={secret}
HOST={self.server_host}
PORT={self.server_port}
CORS_ORIGINS=["{api_origin}","http://localhost:7842"]
DEPLOYMENT_MODE=global_only
SYNC_ENABLED=true
SYNC_INTERVAL_MINUTES=30
"""
        path = env_path()
        path.write_text(content, encoding="utf-8")
        apply_env_to_process(path)
        return path

    def write_manager_config(self) -> None:
        import json

        path = get_app_dir() / "server_manager.json"
        path.write_text(
            json.dumps(
                {
                    "auto_start": self.auto_start,
                    "open_browser": self.open_browser,
                    "host": self.server_host,
                    "port": self.server_port,
                },
                indent=2,
            ),
            encoding="utf-8",
        )


async def _test_database(url: str) -> Tuple[bool, str]:
    try:
        from prisma import Prisma

        db = Prisma(datasource={"url": url})
        await db.connect()
        await db.query_raw("SELECT 1")
        await db.disconnect()
        return True, "Database connection successful"
    except Exception as exc:
        return False, str(exc)


def _ensure_database_exists(config: GlobalSetupConfig) -> Tuple[bool, str]:
    try:
        import psycopg2
        from psycopg2.extensions import ISOLATION_LEVEL_AUTOCOMMIT
    except ImportError:
        return True, "OK"
    try:
        conn = psycopg2.connect(
            host=config.db_host,
            port=config.db_port,
            user=config.db_user,
            password=config.db_password,
            dbname="postgres",
        )
        conn.set_isolation_level(ISOLATION_LEVEL_AUTOCOMMIT)
        cur = conn.cursor()
        cur.execute("SELECT 1 FROM pg_database WHERE datname = %s", (config.db_name,))
        if not cur.fetchone():
            cur.execute(f'CREATE DATABASE "{config.db_name}"')
        cur.close()
        conn.close()
        return True, "OK"
    except Exception as exc:
        return False, f"Database setup failed: {exc}"


def test_database_connection(config: GlobalSetupConfig) -> Tuple[bool, str]:
    url = config.database_url()
    os.environ["DATABASE_URL"] = url
    ok, msg = _ensure_database_exists(config)
    if not ok:
        return False, msg
    return asyncio.run(_test_database(url))


def _run_prisma_command(args: list, log: LogFn) -> Tuple[bool, str]:
    prisma_dir = find_prisma_schema()
    if not prisma_dir:
        return False, "Prisma schema not found"
    cmd = [sys.executable, "-m", "prisma", *args]
    log(f"Running: prisma {' '.join(args)}")
    result = subprocess.run(
        cmd,
        cwd=str(prisma_dir.parent),
        capture_output=True,
        text=True,
        env=os.environ.copy(),
    )
    if result.stdout:
        log(result.stdout.strip())
    if result.returncode != 0:
        return False, (result.stderr or result.stdout or "Prisma failed").strip()
    return True, "OK"


async def _seed_global_data(config: GlobalSetupConfig, log: LogFn) -> Tuple[bool, str]:
    from prisma import Prisma
    from shared.utils.auth import get_password_hash

    db = Prisma()
    await db.connect()

    branch = await db.branch.find_first(where={"name": "Global HQ"})
    if not branch:
        branch = await db.branch.create(
            data={
                "name": "Global HQ",
                "config": {"organization": config.organization_name},
            }
        )
        log("Created Global HQ branch record")

    admin = await db.admin.find_unique(where={"username": config.admin_username})
    if not admin:
        await db.admin.create(
            data={
                "username": config.admin_username,
                "email": config.admin_email or f"{config.admin_username}@global.cafe",
                "fullName": f"{config.organization_name} Owner",
                "role": "global_admin",
                "passwordHash": get_password_hash(config.admin_password),
            }
        )
        log(f"Created owner account: {config.admin_username}")

    await db.disconnect()
    return True, "OK"


def run_full_setup(config: GlobalSetupConfig, log: Optional[LogFn] = None) -> Tuple[bool, str]:
    logger = log or (lambda _m: None)
    try:
        logger("Writing configuration...")
        config.write_env_file()
        config.write_manager_config()

        ok, msg = _run_prisma_command(["generate"], logger)
        if not ok:
            return False, msg
        ok, msg = _run_prisma_command(["db", "push", "--accept-data-loss"], logger)
        if not ok:
            return False, msg

        ok, msg = asyncio.run(_seed_global_data(config, logger))
        if not ok:
            return False, msg

        mark_setup_complete(
            {
                "organization_name": config.organization_name,
                "admin_username": config.admin_username,
                "server_port": config.server_port,
            }
        )
        return True, "Setup complete"
    except Exception as exc:
        return False, str(exc)
