"""Run database setup, schema push, and initial data creation."""

from __future__ import annotations

import asyncio
import os
import secrets
import subprocess
import sys
from dataclasses import dataclass, asdict
from pathlib import Path
from typing import Callable, List, Optional, Tuple

from .install_config import (
    apply_env_to_process,
    env_path,
    find_prisma_schema,
    get_app_dir,
    mark_setup_complete,
)

LogFn = Callable[[str], None]


@dataclass
class SetupConfig:
    cafe_name: str
    branch_name: str
    branch_address: str
    branch_phone: str
    db_host: str
    db_port: int
    db_user: str
    db_password: str
    db_name: str
    admin_username: str
    admin_password: str
    admin_email: str
    server_host: str = "0.0.0.0"
    server_port: int = 8000
    auto_start: bool = True
    open_browser: bool = True

    def database_url(self) -> str:
        from urllib.parse import quote_plus

        user = quote_plus(self.db_user)
        password = quote_plus(self.db_password)
        return (
            f"postgresql://{user}:{password}@{self.db_host}:{self.db_port}/{self.db_name}"
        )

    def write_env_file(self) -> Path:
        secret = secrets.token_hex(32)
        dashboard_origin = f"http://localhost:{self.server_port}"
        dev_origin = "http://localhost:7842"
        content = f"""# Generated by CyberCafe Server Setup
DATABASE_URL={self.database_url()}
SECRET_KEY={secret}
HOST={self.server_host}
PORT={self.server_port}
DASHBOARD_PORT=7842
CORS_ORIGINS=["{dashboard_origin}","{dev_origin}"]
DEPLOYMENT_MODE=local_only
SYNC_ENABLED=false
GLOBAL_SERVER_URL=
BRANCH_ID=1
DNS_BLOCKING=true
PROCESS_BLOCKING=false
URL_FILTERING=false
"""
        path = env_path()
        path.write_text(content, encoding="utf-8")
        apply_env_to_process(path)
        return path

    def write_manager_config(self) -> None:
        import json

        path = get_app_dir() / "server_manager.json"
        existing = {}
        if path.is_file():
            try:
                existing = json.loads(path.read_text(encoding="utf-8"))
            except Exception:
                pass
        existing.update(
            {
                "auto_start": self.auto_start,
                "open_browser": self.open_browser,
                "host": self.server_host,
                "port": self.server_port,
            }
        )
        path.write_text(json.dumps(existing, indent=2), encoding="utf-8")


async def _test_database(url: str) -> Tuple[bool, str]:
    try:
        from prisma import Prisma

        db = Prisma(datasource={"url": url})
        await db.connect()
        await db.query_raw("SELECT 1")
        await db.disconnect()
        return True, "Database connection successful"
    except Exception as exc:
        return False, str(exc)


def test_database_connection(config: SetupConfig) -> Tuple[bool, str]:
    url = config.database_url()
    os.environ["DATABASE_URL"] = url
    ok, msg = _ensure_database_exists(config)
    if not ok:
        return False, msg
    return asyncio.run(_test_database(url))


def _ensure_database_exists(config: SetupConfig) -> Tuple[bool, str]:
    """Create the target database if missing (requires psycopg2)."""
    try:
        import psycopg2
        from psycopg2.extensions import ISOLATION_LEVEL_AUTOCOMMIT
    except ImportError:
        return True, "OK"

    try:
        conn = psycopg2.connect(
            host=config.db_host,
            port=config.db_port,
            user=config.db_user,
            password=config.db_password,
            dbname="postgres",
        )
        conn.set_isolation_level(ISOLATION_LEVEL_AUTOCOMMIT)
        cur = conn.cursor()
        cur.execute("SELECT 1 FROM pg_database WHERE datname = %s", (config.db_name,))
        if not cur.fetchone():
            cur.execute(f'CREATE DATABASE "{config.db_name}"')
        cur.close()
        conn.close()
        return True, "OK"
    except Exception as exc:
        return False, f"Database setup failed: {exc}"


def _run_prisma_command(args: List[str], log: LogFn) -> Tuple[bool, str]:
    prisma_dir = find_prisma_schema()
    if not prisma_dir:
        return False, "Prisma schema not found in installation files"

    cmd = [sys.executable, "-m", "prisma", *args]
    log(f"Running: prisma {' '.join(args)}")
    result = subprocess.run(
        cmd,
        cwd=str(prisma_dir.parent),
        capture_output=True,
        text=True,
        env=os.environ.copy(),
    )
    if result.stdout:
        log(result.stdout.strip())
    if result.returncode != 0:
        err = result.stderr.strip() or result.stdout.strip() or "Prisma command failed"
        return False, err
    return True, "OK"


async def _seed_initial_data(config: SetupConfig, log: LogFn) -> Tuple[bool, str]:
    from prisma import Prisma
    from shared.utils.auth import get_password_hash

    from shared.branding import default_branding_seed

    db = Prisma()
    await db.connect()

    seed_branding = default_branding_seed()
    seed_branding["display_name"] = config.cafe_name or seed_branding["display_name"]

    branch = await db.branch.find_first(where={"name": config.branch_name})
    if not branch:
        branch = await db.branch.create(
            data={
                "name": config.branch_name,
                "address": config.branch_address or None,
                "phone": config.branch_phone or None,
                "config": {
                    "cafe_name": config.cafe_name,
                    "branding": seed_branding,
                },
            }
        )
        log(f"Created branch: {branch.name}")
    else:
        log(f"Using existing branch: {branch.name}")

    admin = await db.admin.find_unique(where={"username": config.admin_username})
    if not admin:
        await db.admin.create(
            data={
                "username": config.admin_username,
                "email": config.admin_email or f"{config.admin_username}@local.cafe",
                "fullName": f"{config.cafe_name} Administrator",
                "role": "branch_admin",
                "branchId": branch.id,
                "passwordHash": get_password_hash(config.admin_password),
            }
        )
        log(f"Created admin user: {config.admin_username}")
    else:
        log(f"Admin already exists: {config.admin_username}")

    await db.disconnect()
    return True, str(branch.id)


def run_full_setup(config: SetupConfig, log: Optional[LogFn] = None) -> Tuple[bool, str]:
    """Write config, push schema, seed branch + admin. Returns (ok, message)."""
    logger = log or (lambda _msg: None)

    try:
        logger("Writing configuration...")
        config.write_env_file()
        config.write_manager_config()

        logger("Generating Prisma client...")
        ok, msg = _run_prisma_command(["generate"], logger)
        if not ok:
            return False, msg

        logger("Applying database schema...")
        ok, msg = _run_prisma_command(["db", "push", "--accept-data-loss"], logger)
        if not ok:
            return False, msg

        logger("Creating branch and administrator...")
        ok, branch_id = asyncio.run(_seed_initial_data(config, logger))
        if not ok:
            return False, branch_id

        env_file = env_path()
        text = env_file.read_text(encoding="utf-8")
        if "BRANCH_ID=1" in text:
            text = text.replace("BRANCH_ID=1", f"BRANCH_ID={branch_id}", 1)
            env_file.write_text(text, encoding="utf-8")

        mark_setup_complete(
            {
                "cafe_name": config.cafe_name,
                "branch_name": config.branch_name,
                "admin_username": config.admin_username,
                "server_port": config.server_port,
            }
        )
        logger("Setup completed successfully.")
        return True, "Setup complete"
    except Exception as exc:
        return False, str(exc)
